document.addEventListener("DOMContentLoaded",function(){
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const meetings=[
{type:"NA",day:"Thursday",time:"19:00",name:"Shrewsbury Newcomers",venue:"St Winefrides Convent",address:"College Hill, Shrewsbury",postcode:"SY1 1LS",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Sunday",time:"19:00",name:"Shrewsbury Sunday",venue:"St Winefrides Convent",address:"College Hill, Shrewsbury",postcode:"SY1 1LS",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Tuesday",time:"14:00",name:"Telford Daytime",venue:"Strickland House",address:"Wellington",postcode:"TF1 3BX",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Friday",time:"11:30",name:"Telford Park Lane",venue:"Park Lane Centre",address:"Woodside, Telford",postcode:"TF7 5QZ",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Tuesday",time:"19:30",name:"Wolverhampton ESH Shares",venue:"St Patrick’s RC Church",address:"299 Wolverhampton Road",postcode:"WV10 0QQ",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Wednesday",time:"19:30",name:"Wolverhampton Spiritual Sisters",venue:"St Patrick’s RC Church",address:"299 Wolverhampton Road",postcode:"WV10 0QQ",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Friday",time:"19:00",name:"Wolverhampton Friday Night",venue:"All Saints Church",address:"All Saints Road",postcode:"WV2 1EL",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Saturday",time:"18:30",name:"Wolverhampton Saturday",venue:"St Mary & St John Church",address:"Snow Hill",postcode:"WV2 4AD",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Monday",time:"19:30",name:"Walsall Monday Message",venue:"CGL Walsall",address:"30 Station Street",postcode:"WS2 9JZ",source:"https://meetings.ukna.org/"},
{type:"NA",day:"Every day",time:"Various",name:"NA Online Meetings",venue:"Online",address:"Official online finder",postcode:"Online",source:"https://meetings.ukna.org/meeting/search/online"},
{type:"AA",day:"Every day",time:"Various",name:"AA Meetings",venue:"Nationwide or online",address:"Search by postcode",postcode:"UK",source:"https://www.alcoholics-anonymous.org.uk/find-a-meeting/"}];
const steps=["Admit powerlessness and that life had become unmanageable.","Believe help and recovery are possible.","Decide to turn towards recovery and support.","Take an honest personal inventory.","Share the truth with someone safe.","Become ready to change harmful patterns.","Ask for help removing those patterns.","List people harmed and become willing to make amends.","Make amends where possible, without causing harm.","Keep taking inventory and admit wrongs quickly.","Use prayer or meditation to stay connected and grounded.","Carry the message and practise these principles."];
const badgeDef=[["First meeting",1],["3 meetings",3],["One week",7],["Two weeks",14],["30 days",30],["60 days",60],["90 days",90],["100 meetings",100]];
let state=loadState();
function byId(id){return document.getElementById(id)}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function loadState(){try{const raw=localStorage.getItem("recovery_companion_fixed");if(raw)return JSON.parse(raw)}catch(e){}return{attended:[],plan:[],goal:3,allowMultiple:false,countOnline:true,mood:""}}
function save(){localStorage.setItem("recovery_companion_fixed",JSON.stringify(state));render()}
function todayKey(){return new Date().toISOString().slice(0,10)}
function toast(text){const el=byId("toast");el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function weekStart(){const d=new Date();const day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(0,0,0,0);return d}
function weeklyCount(){const start=weekStart();return state.attended.filter(x=>new Date(x.date)>=start&&(state.countOnline||x.kind!=="Online")).length}
function streakCount(){let c=0;const set=new Set(state.attended.map(x=>x.date));const d=new Date();while(set.has(d.toISOString().slice(0,10))){c++;d.setDate(d.getDate()-1)}return c}
function xp(){return state.attended.length*10+streakCount()*5}
function level(){return Math.floor(xp()/75)+1}
function encouragement(){if(!state.attended.some(x=>x.date===todayKey()))return"Just one meeting today. In person or online both count.";if(weeklyCount()>=state.goal)return"Weekly goal hit. That is real progress.";if(streakCount()>=7)return"Strong consistency. Keep building.";return"Good start. Keep going."}
function mark(kind){const key=todayKey();if(!state.allowMultiple&&state.attended.some(x=>x.date===key)){toast("Today is already counted");return}state.attended.push({date:key,kind:kind,mood:state.mood||"",note:byId("note").value.trim()});byId("todayMessage").textContent=kind+" meeting counted for today.";byId("note").value="";toast("Meeting counted");save()}
function addToPlan(m){state.plan.push(Object.assign({},m));toast("Added to plan");save()}
function removeFromPlan(i){state.plan.splice(i,1);save()}
window.removeFromPlan=removeFromPlan;
function renderMeetings(){const list=byId("meetingList");const q=byId("searchBox").value.toLowerCase();const df=byId("dayFilter").value;const tf=byId("typeFilter").value;list.innerHTML="";meetings.filter(m=>{const txt=Object.values(m).join(" ").toLowerCase();return(!q||txt.includes(q))&&(!df||m.day===df||m.day==="Every day")&&(!tf||m.type.includes(tf)||(tf==="Online"&&txt.includes("online")))}).forEach(m=>{const map="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(m.venue+" "+m.address+" "+m.postcode);const card=document.createElement("article");card.className="meeting-card";card.innerHTML='<div class="meeting-title">'+esc(m.name)+'</div><span class="pill">'+esc(m.type)+'</span><div class="meeting-meta"><b>'+esc(m.day)+'</b> '+esc(m.time)+'<br>'+esc(m.venue)+'<br>'+esc(m.address)+'<br>'+esc(m.postcode)+'</div><div class="meeting-actions"><button type="button" class="small addBtn">Add to plan</button><a class="small" target="_blank" rel="noopener" href="'+m.source+'">Check source</a><a class="small" target="_blank" rel="noopener" href="'+map+'">Map</a></div>';card.querySelector(".addBtn").addEventListener("click",()=>addToPlan(m));list.appendChild(card)})}
function renderCalendar(){const cal=byId("miniCalendar");cal.innerHTML="";for(let i=13;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);const div=document.createElement("div");div.className="calday"+(state.attended.some(x=>x.date===key)?" done":"");div.textContent=d.getDate();cal.appendChild(div)}}
function renderPlan(){byId("weekPlan").innerHTML=days.map(day=>{const items=state.plan.map((p,index)=>({p,index})).filter(o=>o.p.day===day||o.p.day==="Every day");const body=items.length?items.map(o=>'<div class="plan-item"><span><b>'+esc(o.p.type)+'</b> '+esc(o.p.time||"")+'<br>'+esc(o.p.name||"Chosen meeting")+'<br>'+esc((o.p.venue||"")+" "+(o.p.postcode||""))+'</span><button type="button" onclick="removeFromPlan('+o.index+')">Remove</button></div>').join(""):'<p class="muted">No meeting chosen yet.</p>';return'<div class="day-box"><h3>'+day+'</h3>'+body+'</div>'}).join("")}
function renderJournal(){const entries=state.attended.slice().reverse().filter(x=>x.note||x.mood).slice(0,10);byId("journalList").innerHTML=entries.length?entries.map(x=>'<div class="journal-item"><b>'+esc(x.date)+'</b> • '+esc(x.kind)+' • '+esc(x.mood||"No mood")+'<br>'+esc(x.note||"")+'</div>').join(""):'<p class="muted">No journal entries yet.</p>'}
function render(){byId("goalCount").value=String(state.goal);byId("allowMultiple").checked=!!state.allowMultiple;byId("countOnline").checked=!!state.countOnline;document.querySelectorAll(".moods button").forEach(btn=>btn.classList.toggle("selected",btn.dataset.mood===state.mood));byId("statTotal").textContent=state.attended.length;byId("statWeek").textContent=weeklyCount();byId("statStreak").textContent=streakCount();byId("statLevel").textContent=level();byId("encouragement").textContent=encouragement();byId("xpText").textContent=xp()+" XP • Level "+level()+" • "+state.attended.length+" meetings logged";const percent=Math.min(100,Math.round((weeklyCount()/state.goal)*100));byId("weeklyBar").style.width=percent+"%";byId("weeklyText").textContent=weeklyCount()+" / "+state.goal+" this week";byId("weeklyPercent").textContent=percent+"%";byId("badges").innerHTML=badgeDef.map(b=>'<div class="badge '+(state.attended.length>=b[1]?"earned":"")+'">🏅 '+esc(b[0])+'<br><small>'+(state.attended.length>=b[1]?"Unlocked":"Locked")+'</small></div>').join("");byId("stepsList").innerHTML=steps.map((s,i)=>'<div class="step"><b>Step '+(i+1)+'</b><p>'+esc(s)+'</p></div>').join("");renderCalendar();renderPlan();renderJournal();renderMeetings()}
byId("btnPerson").addEventListener("click",()=>mark("In person"));byId("btnOnline").addEventListener("click",()=>mark("Online"));document.querySelectorAll(".moods button").forEach(btn=>btn.addEventListener("click",()=>{state.mood=btn.dataset.mood;save()}));byId("goalCount").addEventListener("change",()=>{state.goal=Number(byId("goalCount").value);save()});byId("allowMultiple").addEventListener("change",()=>{state.allowMultiple=byId("allowMultiple").checked;save()});byId("countOnline").addEventListener("change",()=>{state.countOnline=byId("countOnline").checked;save()});byId("searchBox").addEventListener("input",renderMeetings);byId("dayFilter").addEventListener("change",renderMeetings);byId("typeFilter").addEventListener("change",renderMeetings);byId("addManual").addEventListener("click",()=>{addToPlan({type:byId("manualType").value,day:byId("manualDay").value,time:byId("manualTime").value||"Time TBC",name:"Chosen meeting",venue:byId("manualPlace").value||"Venue TBC",address:"",postcode:"",source:""});byId("manualTime").value="";byId("manualPlace").value=""});byId("quickPick").addEventListener("click",()=>{const todayName=days[(new Date().getDay()+6)%7];const pick=meetings.find(m=>m.day===todayName)||meetings.find(m=>m.day==="Every day")||meetings[0];byId("quickResult").innerHTML='<article class="meeting-card"><div class="meeting-title">'+esc(pick.name)+'</div><div class="meeting-meta">'+esc(pick.day)+' '+esc(pick.time)+'<br>'+esc(pick.venue)+'<br>'+esc(pick.postcode)+'</div><div class="meeting-actions"><a class="small" target="_blank" rel="noopener" href="'+pick.source+'">Check now</a><button type="button" class="small" id="quickAdd">Add to plan</button></div></article>';byId("quickAdd").addEventListener("click",()=>addToPlan(pick))});
render();
});